switch to inline to fix error

diff --git a/app/azure-pipelines.yml b/app/azure-pipelines.yml
--- a/app/azure-pipelines.yml
+++ b/app/azure-pipelines.yml
@@ -37,11 +37,16 @@ stages:
     - task: SSH@0
       inputs:
         sshEndpoint: 'ec2-ssh-connection'
-        runOptions: 'commands'
-        commands: |
+        inline: |
+          # Check if the container with the name 'counter-service' exists
           if docker ps -a --format "{{.Names}}" | grep -q "counter-service"; then
-            docker stop counter-service || true
-            docker rm counter-service || true
+            echo "Container 'counter-service' found."
+            docker stop counter-service || echo "Error stopping container 'counter-service'."
+            docker rm counter-service || echo "Error removing container 'counter-service'."
+          else
+            echo "Container 'counter-service' not found."
           fi
-          docker pull $(imageName)
-          docker run -d -p 80:80 --name counter-service $(imageName)
+          # Pull the latest Docker image
+          docker pull $(imageName) || echo "Error pulling image '$(imageName)'."
+          # Run the new Docker container
+          docker run -d -p 80:80 --name counter-service $(imageName) || echo "Error starting container 'counter-service'."
